name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          docker build \
            --build-arg FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} \
            --build-arg OKTA_CLIENT_ID=${{ secrets.OKTA_CLIENT_ID }} \
            --build-arg OKTA_CLIENT_SECRET=${{ secrets.OKTA_CLIENT_SECRET }} \
            --build-arg OKTA_METADATA_URL=${{ secrets.OKTA_METADATA_URL }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/oicdapp:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/oicdapp:latest

